version: "3.4"

services:
  scraper:
    build:
      context: scraper
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  mondodb:
    image: mongo
    ports:
      - 27017:27017
  tor-proxy:
    image: dperson/torproxy
